version: '3.8'
x-global-environment: &global-environment
  environment:
    - DOCKER_ENV=1
  env_file:
    - ./.env
services:

  neo4j:
    image: neo4j:community-ubi9
    container_name: neo4j
    volumes:
        - $PWD/neo4j/logs:/logs
        - $PWD/neo4j/config:/config
        - $PWD/neo4j/data:/data
        - $PWD/neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/${PASSWORD_NEO4J}
        - NEO4J_initial_dbms_default__database=graphherb
        - NEO4JLABS_PLUGINS=["apoc"]
        - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j
    restart: always
    <<: *global-environment

  streamlit:
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    networks:
      - neo4j
    <<: *global-environment

networks:
  neo4j:
