x-global-environment: &global-environment
  env_file:
    - ./.env

services:
  neo4j:
    image: neo4j:community-ubi9
    container_name: Neo4j-Container
    volumes:
      - ${PWD_PATH}/backend/database/neo4j/logs:/logs
      - ${PWD_PATH}/backend/database/neo4j/config:/config
      - ${PWD_PATH}/backend/database/neo4j/data:/data
      - ${PWD_PATH}/backend/database/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/${PASSWORD_NEO4J}
      - NEO4J_initial_dbms_default__database=graphherb
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - app_network
    restart: always
    <<: *global-environment

  minio:
    container_name: MinIO-Container
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${USER_MINIO_ROOT}
      MINIO_ROOT_PASSWORD: ${PASSWORD_MINIO_ROOT}
    volumes:
      - ${PWD_PATH}/backend/storage/minio:/data
    command: server --console-address ":9001" /data
    networks:
      - app_network
    <<: *global-environment

  # streamlit:
  #   build:
  #     context: ${PWD_PATH}/frontend/streamlit
  #     dockerfile: Dockerfile
  #   container_name: streamlit
  #   ports:
  #     - "8501:8501"
  #   networks:
  #     - app_network
  #   <<: *global-environment

networks:
  app_network:
    driver: bridge